# https://github.com/GATB/bcalm
bcalm_bin_path: bcalm
bcalm_convert_path: convertToGFA.py
# https://github.com/pfaucon/PBSIM-PacBio-Simulator
#pbsim_bin_path: pbsim
#pbsim_config_path: /home/pesho/libs/PBSIM-PacBio-Simulator/data/model_qc_clr
art_bin_path: art_illumina

# aligners
astarix_bin_path:      /home/pesho/astarix/release/astarix
graphaligner_bin_path: Aligner
vg_bin_path:           vg
pasgal_bin_path:       PaSGAL

# generators
bcalm_bin_path:        bcalm
bcalm_convert_path:    convertToGFA.py

